### ISSUE TITLE
Kotlin performance remarks

### ISSUE THREAD

**Issue by rnentjes** [MarioAriasC/monkey.kt#10]
Hi,

Saw your post on medium and I was intrigued why the kotlin vm benchmark is slower then the go one. And I think I found at least a part of it.

The Instructions typealias copies the bytearray in a couple of extension functions (offset/onset). I suspect the slices in go don't copy the array but just have a wrapper referencing the same array with some variables to point to start and length. You could off course also do this in Kotlin and get a better comparison.

As a test I changed the copy code in Instructions.offset to System.arraycopy and this made it >20% faster already (bit of a hassle as this doesn't work on UByteArray and I had to change it to ByteArray). After this change I see time being spend in MInteger.getValue() calls, which looks like a Kotlin specific performance issue.

Anyway just wanted to share my findings, thanks for the go comparison article.

**Comment by MarioAriasC** [comment]
It is my understanding that Go does indeed "go" directly to the byte array references without creating copies. My implementations of `offset` and `onset` were using the `take` and `takeLast` from the Kotlin collections library that wraps everything on `List<T>` and are very slow

I'll try to experiment with `System.arrayCopy`.

Thanks for your kind words
